Implement local install.

diff --git a/household/bin/cloudAtHome b/household/bin/cloudAtHome
--- a/household/bin/cloudAtHome
+++ b/household/bin/cloudAtHome
@@ -4,12 +4,14 @@ cmdlist() {
     echo "
         The list of commands is:
 
-            backup       - backup up the ghost-db and ghost containers
-            help         - get command help
-            install      - install CloudAtHome components
-            in           - enter interactive command mode
-            quit         - exit interactive mode
-            uninstall    - stop and uninstall all containers (all configuration data will be lost)
+            backup        - backup up the wordpress-db and wordpress containers
+            getovpnclient - Get a client config file for openvpn
+            help          - get command help
+            install       - install CloudAtHome components
+            in            - enter interactive command mode
+            quit          - exit interactive mode
+            uninstall     - stop and uninstall all containers (all configuration data will be lost)
+            upgradecaddycerts - Copy vps caddy certs to local caddy
     "
 }
 
@@ -34,6 +36,16 @@ cmd_help() {
         Not implemented yet.
         "
         ;;
+        getovpnclient) echo "
+    getovpnclient filename [extra_config]
+        Get a client.ovpn config file for the openvpn client container. The filename argument
+        is the full pathname of a file to put the configuration in. The extra_config argument
+        is the full pathname to a file containing extra config lines to be added to the standard
+        config generated by the openvpn server. If the extra_config file does not exist, an editor
+        will be started to create it. See \"dockervpn help getclient\" on the vps server for more 
+        information.
+        "
+        ;;
         help) echo "
     help command
         Display help for command.
@@ -41,13 +53,16 @@ cmd_help() {
         cmdlist
         ;;
         install) echo "
-    install [vps|local|configure]
+    install [vps|local|configure] [openvpn_config]
         Install and run the CloudAtHome docker containers on the vps or locally, or 
         configure/reconfigure the insall variables. With configure, the installer 
-        will be prompted for configuration values such as domain name, ghost database 
+        will be prompted for configuration values such as domain name, wordpress database 
         passwords, etc. On a local install, this cloudAtHome script will also be 
-        copied to /usr/local/bin. All docker containers will be started with restart unless_stopped, 
-        so they should restart on host reboots unless they are stopped before the reboot.
+        copied to /usr/local/bin. On a local install, the openvpn_config parameter is required
+        and it is the pathname to an openvpn client config file generated with the 
+        getovpnclient command, so that command must be run prior to a local install. 
+        All docker containers will be started with restart unless_stopped, so they should 
+        restart on host reboots unless they are stopped before the reboot.
         "
         ;;
         in) echo "
@@ -66,6 +81,14 @@ cmd_help() {
         Remove the cloudAtHome script from /usr/local/bin, stop all the docker containers, and remove all docker
         artifacts (image, volumes, etc.) for each container. All configuration data, databases, blog content, and
         nextcloud content will also be removed.
+        "
+        ;;
+        upgradecaddycerts) echo "
+    upgradecaddycerts
+        This command will copy the caddy certificates from the vps to the local caddy instance. The
+        local caddy instance has automatic certificate renewal disabled as it is in a private network.
+        The vps is on the public network and will periodically renew it's caddy certificates, and when 
+        the local ones expire, the vps certificates will need to be copied to the local instance.
         "
         ;;
     *)
@@ -97,6 +120,50 @@ scp_to_vps() {
 scp_to_vps_tmp() {
     scp -P $SSHPORT $1 $SUDOUSER@cloud.$MYDOMAIN:/tmp
     return $?
+}
+
+scp_from_vps() {
+    scp -P $SSHPORT $SUDOUSER@cloud.$MYDOMAIN:$1 $2
+    return $?
+}
+
+getovpnclient() {
+    if [ -z $1 ]; then
+        echo "Please provide a filename to place configuration into."
+        cmd_help getovpnclient
+        return 1
+    fi
+    source /srv/cloudAtHome/.env
+    local fname=`basename $1`
+    if [ ! -z $2 ]; then
+        if [ ! -f $2 ]; then
+            which nano
+            if [[ $? == 1 ]]; then
+                which vi
+                if [[ $? == 1 ]]; then
+                    echo "Can not find nano or vi editors, please install one of those editors."
+                    return 1
+                fi
+                vi $2
+            else
+                nano $2
+            fi
+        fi
+        if [ ! -f $2 ]; then
+            echo "Please create file $2."
+            cmd_help getovpnclient
+            return 1
+        fi
+        scp_to_vps_tmp $2
+        local customfname=`basename $2`
+        exec_vps_cmd /usr/local/bin/dockervpn getclient /tmp/$fname /tmp/$customfname
+        exec_vps_cmd rm /tmp/$customfname
+    else
+        exec_vps_cmd /usr/local/bin/dockervpn getclient /srv/cloudAtHome/openvpn/configs/$fname
+    fi
+    scp_from_vps /tmp/$fname $1
+    exec_vps_cmd rm /tmp/$fname
+    return 0
 }
 
 install_configure() {
@@ -134,7 +201,7 @@ install_configure() {
     while [ ! -z "$db_rootpassw" ]; do
         case "$db_rootpassw" in
             help) 
-                echo "      Databases are created for the ghost and nextcloud platforms. A new root password is required 
+                echo "      Databases are created for the wordpress and nextcloud platforms. A new root password is required 
       for the database. When the database containers are created, this password will be configured as the root password,
       and any other database user passwords that are required for the platform."
                 unset db_rootpassw
@@ -262,115 +329,12 @@ install_configure() {
         esac
     done
 
-    echo "Ghost blog configuration:"
-    read -p "   Enter SMTP host name ($MAILHOST) : " smtp_host
-    while [ ! -z "$smtp_host" ]; do
-        case "$smtp_host" in
-            help) 
-                echo "      The ghost and nextcloud platforms need the ability to send administrator emails. Enter the smtp
-      host name that can be used to send email."
-                unset smtp_host
-                read -p "   Enter SMTP host name ($MAILHOST) : " smtp_host
-                ;;
-            quit)
-                return 1
-                ;;
-            *)
-                MAILHOST=$smtp_host
-                sed -i "s/MAILHOST=.*/MAILHOST=\"${smtp_host}\"/" /srv/cloudAtHome/.env
-                unset smtp_host
-                ;;
-        esac
-    done
-
-    read -p "   Enter SMTP port number ($MAILPORT) : " smtp_port
-    while [ ! -z "$smtp_port" ]; do
-        case "$smtp_port" in
-            help) 
-                echo "      The ghost and nextcloud platforms need the ability to send administrator emails. Enter the smtp
-      port number that can be used to send email."
-                unset smtp_port
-                read -p "   Enter SMTP port number ($MAILPORT) : " smtp_port
-                ;;
-            quit)
-                return 1
-                ;;
-            *)
-                MAILPORT=$smtp_port
-                sed -i "s/MAILPORT=.*/MAILPORT=${smtp_port}/" /srv/cloudAtHome/.env
-                unset smtp_port
-                ;;
-        esac
-    done
-
-    read -p "   Enter email login user ($MAILUSER) : " email_user
-    while [ ! -z "$email_user" ]; do
-        case "$email_user" in
-            help) 
-                echo "      The ghost and nextcloud platforms need the ability to send administrator emails. Enter the email
-      login user that can be used to send email."
-                unset email_user
-                read -p "   Enter email login user ($MAILUSER) : " email_user
-                ;;
-            quit)
-                return 1
-                ;;
-            *)
-                MAILUSER=$email_user
-                sed -i "s/MAILUSER=.*/MAILUSER=\"${email_user}\"/" /srv/cloudAtHome/.env
-                unset email_user
-                ;;
-        esac
-    done
-
-    read -p "   Enter email user password : " -s email_passw
-    echo ""
-    while [ ! -z "$email_passw" ]; do
-        case "$email_passw" in
-            help) 
-                echo "      The ghost and nextcloud platforms need the ability to send administrator emails. Enter the email
-      login password that can be used to send email."
-                unset email_passw
-                read -p "   Enter email user password : " -s email_passw
-                echo ""
-                ;;
-            quit)
-                return 1
-                ;;
-            *)
-                MAILPASSW=$email_passw
-                sed -i "s/MAILPASSW=.*/MAILPASSW=\"${email_passw}\"/" /srv/cloudAtHome/.env
-                unset email_passw
-                ;;
-        esac
-    done
-
-    read -p "   Enter email from identity ($MAILFROM) : " email_identity
-    while [ ! -z "$email_identity" ]; do
-        case "$email_identity" in
-            help) 
-                echo "      The ghost and nextcloud platforms need the ability to send administrator emails. Enter the name
-      and email address that will display in the email from field."
-                unset email_identity
-                read -p "   Enter email from identity ($MAILFROM) : " email_identity
-                ;;
-            quit)
-                return 1
-                ;;
-            *)
-                MAILFROM=$email_identity
-                sed -i "s/MAILFROM=.*/MAILFROM=\"${email_identity}\"/" /srv/cloudAtHome/.env
-                unset email_identity
-                ;;
-        esac
-    done
-
     echo "Openvpn configuration:"
     read -p "   Enter OpenVPN port number ($OPENVPNPORT) : " openvpn_port
     while [ ! -z "$openvpn_port" ]; do
         case "$openvpn_port" in
             help) 
-                echo "      The ghost and nextcloud platforms need the ability to send administrator emails. Enter the name
+                echo "      The wordpress and nextcloud platforms need the ability to send administrator emails. Enter the name
       and email address that will display in the email from field."
                 unset openvpn_port
                 read -p "   Enter OpenVPN port number ($OPENVPNPORT) : " -s openvpn_port
@@ -441,6 +405,7 @@ install_vps() {
     [ ! -f "/srv/cloudAtHome/vps/caddy/Caddyfile" ] && cp vps/Caddyfile /srv/cloudAtHome/vps/caddy/Caddyfile
     sed -i "/marker one/,/marker two/{s%https:.*%https://${MYDOMAIN}, https://www.${MYDOMAIN} \{%}" /srv/cloudAtHome/vps/caddy/Caddyfile
     sed -i "/marker two/,/marker three/{s%https://cloud.*%https://cloud.${MYDOMAIN}:443 \{%}" /srv/cloudAtHome/vps/caddy/Caddyfile
+    sed -i "/marker three/,/marker four/{s%https://cloud.*%https://cloud.${MYDOMAIN}:8443 \{%}" /srv/cloudAtHome/vps/caddy/Caddyfile
     sed -i "/marker zero/,/marker one/{s/email.*/email $LETSENCRYPTEMAIL/}" /srv/cloudAtHome/vps/caddy/Caddyfile
     cat /srv/cloudAtHome/vps/caddy/Caddyfile
     read -p $'\n'"Please verify contents of vps Web Proxy configuration file. Proceed (Yes/no/edit) ? " answer
@@ -472,6 +437,7 @@ install_vps() {
     fi
 
     # Configure openvpn for the vps
+    docker context use default
     mkdir -p /srv/cloudAtHome/backups
     docker pull castone38/dockervpn:latest
     docker run --rm castone38/dockervpn:latest cat /opt/dockervpn >./dockervpn
@@ -503,6 +469,7 @@ install_vps() {
         return 1
     fi
 
+    docker context create vps --docker "host=ssh://$SUDOUSER@cloud.$MYDOMAIN:$SSHPORT"
     touch /srv/cloudAtHome/.vps_installed
     return 0
 }
@@ -517,6 +484,57 @@ install_local() {
     if [[ $? != 0 ]]; then
         return 1
     fi
+    if [ ! -f $2 ]; then
+        echo "Openvpn config file $2 does not exist."
+        cmd_help install
+        return 1
+    fi
+
+    docker context use default
+    mkdir -p /srv/cloudAtHome/openvpn/data
+    mkdir -p /srv/cloudAtHome/caddy/data
+    [ ! -f "/srv/cloudAtHome/caddy/Caddyfile" ] && cp Caddyfile /srv/cloudAtHome/caddy/Caddyfile
+    sed -i "/marker two/,/marker three/{s%https://cloud.*%https://cloud.${MYDOMAIN}:443 \{%}" /srv/cloudAtHome/caddy/Caddyfile
+    sed -i "/marker zero/,/marker two/{s/email.*/email $LETSENCRYPTEMAIL/}" /srv/cloudAtHome/caddy/Caddyfile
+    cat /srv/cloudAtHome/caddy/Caddyfile
+    read -p $'\n'"Please verify contents of vps Web Proxy configuration file. Proceed (Yes/no/edit) ? " answer
+    if [ ! -z "$answer" ]; then
+        while [[ $answer != "Y" && $answer != "y" && $answer != "Yes" && $answer != "yes" ]]; do
+            if [[ $answer == "N" || $answer == "n" || $answer == "no" ]]; then
+                return 1
+            fi
+            if [[ $answer == "E" || $answer == "e" || $answer == "edit" ]]; then
+                which nano
+                if [[ $? == 1 ]]; then
+                    which vi
+                    if [[ $? == 1 ]]; then
+                        echo "Can not find nano or vi editors, please install one of those editors."
+                        return 1
+                    fi
+                    vi /srv/cloudAtHome/caddy/Caddyfile
+                else
+                    nano /srv/cloudAtHome/caddy/Caddyfile
+                fi
+            fi
+            unset answer
+            cat /srv/cloudAtHome/caddy/Caddyfile
+            read -p "Please verify contents of vps Web Proxy configuration file. Proceed (Yes/no/edit) ? " answer
+            if [ -z "$answer" ]; then
+                answer="Y"
+            fi
+        done
+    fi
+    mkdir -p /srv/cloudAtHome/caddy/config
+    exec_vps_cmd tar -C /srv/cloudAtHome/caddy/data -cjf /tmp/caddycerts.tar.bz2 caddy
+    scp_from_vps /tmp/caddycerts.tar.bz2 /tmp/caddycerts.tar.bz2
+    tar -C /srv/cloudAtHome/caddy/data -xjf /tmp/caddycerts.tar.bz2
+    rm /tmp/caddycerts.tar.bz2
+    cp $2 /srv/cloudAtHome/openvpn/data/vpn.conf
+    cp docker-compose.yml /srv/cloudAtHome
+    cd /srv/cloudAtHome
+    echo "Starting local containers. This can take a few minutes to complete."
+    docker-compose up -d
+
     return 0
 }
 
@@ -556,7 +574,7 @@ install() {
             echo "CloudAtHome vps install complete."
             ;;
         local)
-            install_local
+            install_local "$@"
             if [[ $? != 0 ]]; then
                 return 1
             fi
@@ -572,6 +590,7 @@ install() {
             ;;
     esac
 
+    [ $? != 0 ] && return $?
     return 0
 }
 
@@ -594,6 +613,7 @@ uninstall() {
             rm -f /srv/cloudAtHome/backups/vps_openvpn_config.tar.bz2
             rm -rf /srv/cloudAtHome/vps
             rm -f /srv/cloudAtHome/.vps_installed
+            docker context rm vps
             echo "CloudAtHome vps uninstall complete."
             ;;
         local)
@@ -606,13 +626,30 @@ uninstall() {
             ;;
     esac
 
+    [ $? != 0 ] && return $?
     return 0
+}
+
+upgradecaddycerts() {
+    amiroot=`id -u`
+    if (( $amiroot !=0 )); then
+        echo "You must run this conmand as root, or with sudo."
+        return 1
+    fi
+
+    exec_vps_cmd tar -cjf /tmp/caddycerts.tar.bz2 /srv/cloudAtHome/caddy/data
+    scp_from_vps /tmp/caddycerts.tar.bz2 /tmp/caddycerts.tar.bz2
+    tar -C /srv/cloudAtHome/caddy/data -xjf /tmp/caddycerts.tar.bz2
+    rm /tmp/caddycerts.tar.bz2
 }
 
 process_command() {
     case "${cmd_array[0]}" in
         backup)
             backup
+            ;;
+        getovpnclient)
+            getovpnclient "${cmd_array[@]:1}"
             ;;
         help)
             if [ -z "${cmd_array[@]:1:1}" ]; then
@@ -639,6 +676,9 @@ process_command() {
             return 1
         ;;
     esac
+
+    [ $? != 0 ] && return $?
+    return 0
 }
 
 interactive() {
@@ -647,11 +687,13 @@ interactive() {
         process_command
         read -p "--> " -a cmd_array
     done
+    return 0
 }
 
 
 IFS=' '
 read -a cmd_array <<<"$@"
 process_command
+[ $? != 0 ] && exit $?
 
 exit 0
